#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600
#define PARTICLE_RADIUS 3.0f

#define MAX_LEFT PARTICLE_RADIUS
#define MAX_RIGHT (WINDOW_WIDTH - PARTICLE_RADIUS)
#define MAX_TOP PARTICLE_RADIUS
#define MAX_BOTTOM (WINDOW_HEIGHT - PARTICLE_RADIUS)

#define GRAVITY 250.0f
#define DAMPING_FACTOR 0.9f

#define GRID_CELL_SIZE (PARTICLE_RADIUS * 2.0f)
#define GRID_WIDTH (WINDOW_WIDTH / GRID_CELL_SIZE)
#define GRID_HEIGHT (WINDOW_HEIGHT / GRID_CELL_SIZE)
#define MAX_PARTICLES_PER_CELL 16

#endif // CONSTANTS_H
