#pragma once

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600
#define PARTICLE_RADIUS 5.0f

#define MAX_LEFT PARTICLE_RADIUS
#define MAX_RIGHT (WINDOW_WIDTH - PARTICLE_RADIUS)
#define MAX_TOP PARTICLE_RADIUS
#define MAX_BOTTOM (WINDOW_HEIGHT - PARTICLE_RADIUS)

#define GRAVITY 0.05f
#define DAMPING_FACTOR 0.8f